#!/usr/bin/env node
// Builds every generated artefact from catalog/sources/*.json.
//
//   node scripts/build.mjs           # write
//   node scripts/build.mjs --check   # fail if anything is out of date (CI)
//
// Generates:
//   catalog/index.json  - the aggregate skills read at runtime
//   CREDITS.md          - full attribution, one section per source
//   README.md           - the catalog table, between its markers
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, loadSources, loadSkills, taxonomy, replaceBlock } from './lib.mjs';
import { daysBetween, REVIEW_MAX_DAYS, STALE_DAYS } from './upstream.mjs';

const check = process.argv.includes('--check');
const sources = loadSources().map((s) => s.data);
const T = taxonomy();
const stale = [];

function emit(relPath, content) {
  const abs = join(ROOT, relPath);
  const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (current === content) return;
  if (check) { stale.push(relPath); return; }
  writeFileSync(abs, content);
  console.log(`  wrote ${relPath}`);
}

// ---------------------------------------------------------------- index.json
// Skills read this file instead of globbing the sources directory, so a skill
// only ever needs one fetch to know the whole catalog.
const byCapability = {};
const byStack = {};
const byStyle = {};
for (const s of sources) {
  for (const c of s.capabilities || []) (byCapability[c] ??= []).push(s.id);
  for (const k of s.stacks || []) (byStack[k] ??= []).push(s.id);
  for (const t of s.style_tags || []) (byStyle[t] ??= []).push(s.id);
}
const sortKeys = (o) => Object.fromEntries(Object.keys(o).sort().map((k) => [k, o[k].sort()]));

const index = {
  $comment: 'GENERATED by scripts/build.mjs from catalog/sources/*.json. Do not edit by hand.',
  generator: 'scripts/build.mjs',
  count: sources.length,
  taxonomy: {
    capabilities: Object.keys(T.capabilities).sort(),
    stacks: Object.keys(T.stacks).sort(),
    style_tags: Object.keys(T.style_tags).sort(),
  },
  by_capability: sortKeys(byCapability),
  by_stack: sortKeys(byStack),
  by_style_tag: sortKeys(byStyle),
  sources,
};
emit('catalog/index.json', JSON.stringify(index, null, 2) + '\n');

// ------------------------------------------------------------ skills/index.json
// Generated from each SKILL.md's frontmatter so the catalog of skills can never
// drift from the skills themselves. `uses` is derived by matching the catalog
// repo URLs a skill cites, which makes the skill <-> source link navigable both ways.
const byId = Object.fromEntries(sources.map((s) => [s.id, s]));
const skills = loadSkills(byId);
for (const sk of skills) {
  if (!sk.description) throw new Error(`skills/${sk.name}/SKILL.md has no description in its frontmatter`);
  if (sk.name !== sk.dir.split('/')[1]) throw new Error(`skills/${sk.dir.split('/')[1]}: frontmatter name "${sk.name}" must match the directory`);
}
emit('skills/index.json', JSON.stringify({
  $comment: 'GENERATED by scripts/build.mjs from skills/*/SKILL.md frontmatter. Do not edit by hand.',
  count: skills.length,
  skills,
}, null, 2) + '\n');

// ----------------------------------------------------------------- CREDITS.md
const KIND_LABEL = {
  'component-library': 'Component library',
  'curated-list': 'Curated list',
  'agent-skills': 'Agent skills',
  'design-language': 'Design language',
  'workshop-tool': 'Workshop tool',
  'generative-tool': 'Generative tool',
};

const credits = [];
credits.push('# Credits');
credits.push('');
credits.push('<!-- GENERATED by scripts/build.mjs. Edit catalog/sources/*.json instead. -->');
credits.push('');
credits.push('Every project below is the work of its own authors and maintainers, published under its own license.');
credits.push('This repository indexes and links to them. It does not vendor, fork, or re-license their content.');
credits.push('');
credits.push('If you maintain one of these projects and want the entry changed or removed, open an issue and we will act on it.');
credits.push('');
credits.push(`Indexed sources: **${sources.length}**`);
credits.push('');
for (const s of sources) {
  credits.push(`## ${s.name}`);
  credits.push('');
  credits.push(`- **Author:** [${s.author.name}](${s.author.url})`);
  if (s.author.credit_note) credits.push(`- **Also credit:** ${s.author.credit_note}`);
  credits.push(`- **Repository:** ${s.repo}`);
  if (s.homepage) credits.push(`- **Homepage:** ${s.homepage}`);
  credits.push(`- **License:** ${s.license}${s.license_url ? ` — ${s.license_url}` : ''}`);
  credits.push(`- **Kind:** ${KIND_LABEL[s.kind] || s.kind}`);
  credits.push(`- **Catalog id:** \`${s.id}\``);
  credits.push('');
  credits.push(`> ${s.summary}`);
  credits.push('');
  if (s.notes) { credits.push(`**Note:** ${s.notes}`); credits.push(''); }
}
credits.push('---');
credits.push('');
credits.push('## About this repository');
credits.push('');
credits.push('The catalog metadata, skills, scripts, and documentation in this repository are MIT licensed (see `LICENSE`).');
credits.push('That license covers this repository\'s own work only. Anything you pull from an indexed source arrives under that');
credits.push('source\'s license, and any third-party asset reached through a curated list carries the terms of wherever it lives.');
credits.push('');
emit('CREDITS.md', credits.join('\n'));

// ------------------------------------------------------------- README table
const rows = ['| Source | Author | Kind | Good for | License |', '| --- | --- | --- | --- | --- |'];
for (const s of sources) {
  const caps = (s.capabilities || []).slice(0, 3).join(', ');
  rows.push(`| [${s.name}](${s.repo}) | [${s.author.name}](${s.author.url}) | ${KIND_LABEL[s.kind] || s.kind} | ${caps} | ${s.license} |`);
}
// Freshness table - how recent each upstream is, and when a person last
// reviewed the entry. Ages are measured against each entry's own `checked`
// date, never the clock, so `build.mjs --check` gives the same answer any day.
const lastChecked = sources.map((s) => s.upstream?.checked).filter(Boolean).sort().pop();
const fresh = [];
if (lastChecked) {
  fresh.push(`Last checked ${lastChecked}. ⚠️ marks an upstream with no commits in a year, or an entry not reviewed in ${REVIEW_MAX_DAYS} days.`, '');
}
fresh.push('| Source | Last upstream commit | Age when checked | Latest release | Last reviewed | Stars |', '| --- | --- | --- | --- | --- | --- |');
for (const s of [...sources].sort((a, b) => (b.upstream?.last_commit || '').localeCompare(a.upstream?.last_commit || ''))) {
  const u = s.upstream || {};
  const stars = s.metrics?.stars?.toLocaleString('en-US') ?? '—';
  const release = u.latest_release ? `\`${u.latest_release}\`` : '—';
  const reviewedOn = s.review?.date;
  const reviewed = !reviewedOn ? 'never ⚠️'
    : u.checked && daysBetween(reviewedOn, u.checked) > REVIEW_MAX_DAYS ? `${reviewedOn} ⚠️` : reviewedOn;
  if (!u.last_commit) { fresh.push(`| [${s.name}](${s.repo}) | not checked yet | — | ${release} | ${reviewed} | ${stars} |`); continue; }
  const d = Math.max(0, daysBetween(u.last_commit, u.checked));
  const age = d === 0 ? 'same day' : d === 1 ? '1 day' : `${d} days`;
  const flag = u.archived ? ' **archived**' : d > STALE_DAYS ? ' ⚠️' : '';
  fresh.push(`| [${s.name}](${s.repo}) | ${u.last_commit.slice(0, 10)}${flag} | ${age} | ${release} | ${reviewed} | ${stars} |`);
}

// Skills table, generated from frontmatter.
const skillRows = ['| Skill | What it does |', '| --- | --- |'];
for (const sk of skills) {
  const first = (sk.description || '').split(/(?<=\.)\s/)[0];
  skillRows.push(`| [\`${sk.name}\`](${sk.file}) | ${first} |`);
}

// Inline credits, so attribution is visible on the repo's front page.
const creditRows = ['| Project | Author | License |', '| --- | --- | --- |'];
for (const s of sources) {
  const extra = s.author.credit_note ? ` <sub>${s.author.credit_note.replace(/\s*\(https?:[^)]*\)/g, '')}</sub>` : '';
  creditRows.push(`| [${s.name}](${s.repo}) | [${s.author.name}](${s.author.url})${extra} | ${s.license} |`);
}

const readmePath = join(ROOT, 'README.md');
if (existsSync(readmePath)) {
  let readme = readFileSync(readmePath, 'utf8');
  readme = replaceBlock(readme, 'catalog-table', rows.join('\n'));
  readme = replaceBlock(readme, 'skills-table', skillRows.join('\n'));
  readme = replaceBlock(readme, 'freshness-table', fresh.join('\n'));
  readme = replaceBlock(readme, 'credits-table', creditRows.join('\n'));
  emit('README.md', readme);
}

if (check && stale.length) {
  console.error(`\nGenerated files are out of date: ${stale.join(', ')}`);
  console.error('Run: node scripts/build.mjs\n');
  process.exit(1);
}
console.log(check ? 'generated files are up to date' : `build ok - ${sources.length} source(s), ${skills.length} skill(s)`);
